In [1]:
import numpy as np
from torch import nn
import torch

In [2]:
# kernel = torch.tensor([1])
kernel = torch.tensor([[0, 0], [0, 1]])
# kernel = torch.tensor([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
conv2d_layer_small = nn.Conv2d(
    in_channels=1, out_channels=1, kernel_size=kernel.shape[0], stride=1, padding=1
)
# Initialize the kernel for a simple detector
with torch.no_grad():
    bias = torch.tensor([0])

    conv2d_layer_small.weight[0, 0, :, :] = kernel
    conv2d_layer_small.bias[0] = bias

    input = torch.tensor(np.arange(16).reshape(1, 1, 4, 4), dtype=torch.float32, requires_grad=True)

output = conv2d_layer_small(input)
print(output)
print(output.shape)

output.backward(torch.ones_like(output))

tensor([[[[ 0.,  1.,  2.,  3.,  0.],
          [ 4.,  5.,  6.,  7.,  0.],
          [ 8.,  9., 10., 11.,  0.],
          [12., 13., 14., 15.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]], grad_fn=<ConvolutionBackward0>)
torch.Size([1, 1, 5, 5])


In [3]:

# Extract the gradients
d_filters_small_pytorch = conv2d_layer_small.weight.grad
d_biases_small_pytorch = conv2d_layer_small.bias.grad

print(d_filters_small_pytorch)
print(d_biases_small_pytorch)
print(input.grad)


tensor([[[[120., 120.],
          [120., 120.]]]])
tensor([25.])
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
